### ISSUE TITLE
Pagination doesn't seem to work

### ISSUE THREAD

**Issue by fraba** [simonlindgren/2wttr#1]
I can't obtain more page than set in `max_results`: indeed I get exactly that number.

**Comment by fraba** [comment]
OK, it seems to work now. `pagination_token` needs to be replaced with `next_token` and `query_params` with `params`.

**Comment by fgais** [comment]
Hi fraba, where exactly did you replace those?

**Comment by simonlindgren** [comment]
Thanks for pointing this out @fraba 
I have corrected the errors you identified in the code!
@fgais It should work now!
